[package]
edition = "2021"
name = "napi-rs_simple-git"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
git2 = { version = "0.14", features = ["vendored-libgit2", "vendored-openssl"] }
napi = { version = "2.3.0-canary.1", default-features = false, features = [
  "napi3",
] }
napi-derive = { version = "2.3.0-canary.1" }
once_cell = "1"
parking_lot = "0.12"

[target.'cfg(all(target_os = "linux", target_env = "gnu", any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
dirs = "4"

[build-dependencies]
napi-build = "1"

[profile.release]
codegen-units = 1
lto = true
