/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getFileLatestModifiedDateByGitAsync(gitDir: string, filepath: string, signal?: AbortSignal | undefined | null): Promise<number>
export function getFileLatestModifiedDateByGit(gitDir: string, filepath: string): number
